id: O96FB467A
source: null
source_file: null
initial_creation_type: input
imported: '2022-06-06T10:59:44.851245'
last_modified: '2022-06-06T10:59:44.851265'
parser: null
source_metadata:
  text_id: D3871
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
